// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CheCoxshall.Battleship.Core.Test
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class BattleshipsBoardSetupFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BattleshipsBoardSetup.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Battleships Board Setup", "\tMake sure the game board is correctly populated before starting a game", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Battleships Board Setup")))
            {
                global::CheCoxshall.Battleship.Core.Test.BattleshipsBoardSetupFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ensure Readiness")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Battleships Board Setup")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("boardSetup")]
        public virtual void EnsureReadiness()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure Readiness", new string[] {
                        "boardSetup"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I have placed an aircraftcarrier horizontally at cell A1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And("I have placed a battleship vertically at cell A2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I have placed a cruiser vertically at cell B2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I have placed a destroyer vertically at cell C2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I have placed a submarine vertically at cell D2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("the game board should be ready", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ensure I cannot start a game without placing all of my ships")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Battleships Board Setup")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("boardSetup")]
        public virtual void EnsureICannotStartAGameWithoutPlacingAllOfMyShips()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure I cannot start a game without placing all of my ships", new string[] {
                        "boardSetup"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I have placed an aircraftcarrier horizontally at cell A1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.And("I have placed a battleship vertically at cell A2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I have placed a cruiser vertically at cell B2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I have placed a destroyer vertically at cell C2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.Then("the game board should not be ready", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ensure game board does not allow overlapping ships")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Battleships Board Setup")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gameBoard")]
        public virtual void EnsureGameBoardDoesNotAllowOverlappingShips()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure game board does not allow overlapping ships", new string[] {
                        "gameBoard"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Ship Type",
                        "Orientation",
                        "Cell"});
            table1.AddRow(new string[] {
                        "aircraftcarrier",
                        "horizontally",
                        "A1"});
            table1.AddRow(new string[] {
                        "battleship",
                        "vertically",
                        "B1"});
#line 23
 testRunner.Given("I have placed the following ships", ((string)(null)), table1, "Given ");
#line 27
 testRunner.Then("the game board should have thrown a CannotPlaceException with the message \'Ships " +
                    "may not overlap.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ensure game board does not allow ships to fall off the edge of the world")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Battleships Board Setup")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gameBoard")]
        public virtual void EnsureGameBoardDoesNotAllowShipsToFallOffTheEdgeOfTheWorld()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure game board does not allow ships to fall off the edge of the world", new string[] {
                        "gameBoard"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I have placed an aircraftcarrier horizontally at cell G1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.Then("the game board should have thrown a CannotPlaceException with the message \'Ship e" +
                    "xtends beyond board boundaries.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ensure game board does not allow duplicate ships")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Battleships Board Setup")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("gameBoard")]
        public virtual void EnsureGameBoardDoesNotAllowDuplicateShips()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure game board does not allow duplicate ships", new string[] {
                        "gameBoard"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Ship Type",
                        "Orientation",
                        "Cell"});
            table2.AddRow(new string[] {
                        "aircraftcarrier",
                        "horizontally",
                        "A1"});
            table2.AddRow(new string[] {
                        "aircraftcarrier",
                        "vertically",
                        "B1"});
#line 36
 testRunner.Given("I have placed the following ships", ((string)(null)), table2, "Given ");
#line 40
 testRunner.Then("the game board should have thrown a CannotPlaceException with the message \'This t" +
                    "ype of ship has already been placed.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
